In [20]:
from pathlib import Path
import torch
import esm
import biotite.structure.io as bsio
import pandas as pd
from proteinttt.models.esmfold import ESMFoldTTT, DEFAULT_ESMFOLD_TTT_CFG

# Feb 2026

In [21]:
res_dir = Path("/scratch/project/open-35-8/pimenol1/ProteinTTT/ProteinTTT_fresh/data/bfvd/bfvd_sample_best/")
dir_esmfold = res_dir / "predicted_structures" / "ESMFold"
dir_proteinttt = res_dir / "predicted_structures" / "ESMFold_ProteinTTT"
df_bfvd = pd.read_csv(res_dir / "results.csv", sep=",")
df_bfvd

,id,nmsa,version,sequence,pLDDT_ESMFold,pLDDT_ProteinTTT,pLDDT_ColabFold,sequence_length,lddt_ProteinTTT,tm_score_ProteinTTT,lddt_ESMFold,tm_score_ESMFold
0,A0A059T6Q4,19,BASE+LOGAN+12CY,MKEKCSIEISYYNGEDKLTGKVVWVVLDKEEGIQFVLTEKPEDEYF...,50.321796,75.635233,42.065870,88,NaN,NaN,NaN,NaN
1,A0A060AHT0,91,BASE,MKQEIESIKIEFTFGEMSWDGCYVTFQQDWSDYSWFRSENSFVTSS...,46.781654,85.521093,44.442511,81,NaN,NaN,NaN,NaN
2,A0A075M4K8,24,BASE+LOGAN+12CY,MIPEVGKQYFGYLPVAMENYEEPYILVYSHKFESEYNGKTYWVFDA...,58.193550,74.748096,37.893749,166,NaN,NaN,NaN,NaN
3,A0A0A0PZG7,4,BASE+LOGAN+12CY,MKIQELLSQLKKFAEFKEFYGFVVNPSGSFSQSYTLDACMIADIKE...,61.730103,78.435108,45.662976,108,NaN,NaN,NaN,NaN
4,A0A0F6R7R7,5,BASE+LOGAN+12CY,MYRVYRRIKNPHKSELESRKVGYIFRGLPTISGNVAEIDEFEETVR...,44.556984,88.185425,50.080709,58,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
305,UPI001F1377E3,1386,BASE,MNDKIYFVTILVKQFSKLLYEIETQLLLARICSTESVNKKQLQITI...,83.788234,83.788234,41.072215,292,NaN,NaN,NaN,NaN
306,UPI0023292547,11,BASE+LOGAN+12CY,MVGYSREMWEVLMGLPSTSRSDAVNLSFAKFGHIIKAWVEGCNIEI...,37.487404,94.512179,38.947581,121,NaN,NaN,NaN,NaN
307,W6JLA7,97,BASE,MFNSKIITDNFNMSYKIMNNNLNINFNKIYNSTHKIDVLDKCFVIY...,34.318183,69.363117,34.711188,251,NaN,NaN,NaN,NaN
308,W8CZD8,41,BASE,MYSFIQEKKVMYNNFDNKKKLIYVQMAAATMQDLLNLTERAKTTAL...,49.529719,69.337458,34.425733,229,NaN,NaN,NaN,NaN
309,X5I2M5,3,BASE,MIIASFMDLTLDVHIRVECRRVTVTLVEYKLVYVKITTGELVLCQP...,55.783633,84.800817,51.324650,73,NaN,NaN,NaN,NaN

In [22]:
df_teo = pd.read_csv("/scratch/project/open-35-8/antonb/ttt/ProteinTTT/data/teo/Top_Candidate_TTT.txt", sep="\t")
df_teo["id"] = df_teo["Prot"].str.split("_").str[0]
# Merge df_bfvd into df_teo on column "id", bringing in specified columns
merge_cols = ["id", "nmsa", "pLDDT_ESMFold", "pLDDT_ProteinTTT", "pLDDT_ColabFold"]
df_teo = pd.merge(df_teo, df_bfvd[merge_cols], on="id", how="left")
df_teo["pLDDT_ProteinTTT - pLDDT_ESMFold"] = df_teo["pLDDT_ProteinTTT"] - df_teo["pLDDT_ESMFold"]

df_teo

,Prot,Foldseek homolog,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,CLEAN annotation,Unnamed: 7,Agreement,maxsep_top1_ec,...,NoveltyScore_0to10,FeasibilityScore_0to10,EvidenceConfidence_0to1,PredictedCategory,id,nmsa,pLDDT_ESMFold,pLDDT_ProteinTTT,pLDDT_ColabFold,pLDDT_ProteinTTT - pLDDT_ESMFold
0,A0A6J5RXK7_A,Nascent polypeptide complex,NaN,NaN,EC:5.4.99.4,0.0017,EC 5.4.99.5 (distance 0.0008): chorismate muta...,NaN,no,EC:5.4.99.4,...,10,10,0.974,aromatic_aa_biosynth,A0A6J5RXK7,237,84.091550,86.426951,52.110596,2.335400
1,A0A6M3YL53_A,tRNA thiolase,NaN,NaN,EC:1.12.1.2,0.0135,EC 1.12.1.2 (distance 0.0001): hydrogen dehydr...,NaN,no,EC:1.12.1.2,...,5,8,0.797,translation_related,A0A6M3YL53,3,87.581146,87.581146,44.067188,0.000000
2,A0A0A0PZG7_A,UPF0134 protein,NaN,NaN,EC:2.5.1.83,0.0001,EC 2.5.1.83 (distance 0.0001): hexaprenyl-diph...,NaN,no,EC:2.5.1.83,...,5,8,0.998,other_or_unclear,A0A0A0PZG7,4,61.730103,78.435108,45.662976,16.705006
3,A0A0U4IQ41_A,Unclear function,NaN,NaN,EC:2.1.1.86,0.0230,Methyl transferase,NaN,no,EC:2.1.1.86,...,4,7,0.700,other_or_unclear,A0A0U4IQ41,4,73.183200,79.778736,46.510100,6.595536
4,A0A1V0SB57_A,Glutamyl-tRNA reductase,NaN,NaN,EC:5.4.99.5,0.0128,EC 5.4.99.5 (distance 0.0008): chorismate muta...,NaN,no,EC:5.4.99.5,...,5,8,0.808,translation_related,A0A1V0SB57,63,70.243154,81.974876,45.513693,11.731722
5,A0A6J7WFZ2_A,"Enzymatic, unclear susbstract",NaN,NaN,EC:4.2.2.7,0.0000,EC 4.2.2.7 (distance 0.0000): heparin lyase. |...,NaN,no,EC:4.2.2.7,...,5,8,1.000,other_or_unclear,A0A6J7WFZ2,9,60.252242,87.905096,50.881623,27.652853
6,A0A8S5LWU4_A,Structural or trna ligase,NaN,NaN,EC:4.3.2.2,0.0016,EC 4.3.2.2 (distance 0.0016): adenylosuccinate...,NaN,no,EC:4.3.2.2,...,6,9,0.976,translation_related,A0A8S5LWU4,47,56.550895,88.123978,46.298609,31.573083
7,B3FIV3_A,Ribosomal protein,NaN,NaN,EC:1.3.1.91,0.0001,t rna synthase,NaN,no,EC:1.3.1.91,...,5,8,0.976,other_or_unclear,B3FIV3,36,45.162235,83.311458,37.567360,38.149223
8,X5I2M5_A,tyrosine phosphatase,NaN,NaN,EC:1.14.13.130,0.0001,EC 1.14.13.130 (distance 0.0003): pyrrole-2-ca...,NaN,no,EC:1.14.13.130,...,9,10,0.908,aromatic_aa_biosynth,X5I2M5,3,55.783633,84.800817,51.324650,29.017183
9,A0A2H4UUY1_A,mRNA-capping enzyme subunit beta,NaN,NaN,EC:3.1.21.4,0.0875,EC 3.1.21.4 (distance 0.0875): type II site-sp...,NaN,no,EC:3.1.21.4,...,2,8,0.592,mrna_capping,A0A2H4UUY1,112,33.916898,78.850062,33.684105,44.933164
10,W8CZD8_A,Ubiquitin chemistry,NaN,NaN,EC:5.4.99.5,0.0022,EC 5.4.99.5 (distance 0.0022): chorismate muta...,NaN,no,EC:5.4.99.5,...,6,10,0.857,ubiquitin_pathway,W8CZD8,41,49.529719,69.337458,34.425733,19.807739
11,A0A249XSF4_A,"Unclear, AA transferase related",NaN,NaN,EC:1.14.13.25,0.0065,EC 1.14.13.25 (distance 0.0002): methane monoo...,NaN,no,EC:1.14.13.25,...,4,7,0.778,other_or_unclear,A0A249XSF4,41,63.813540,83.285551,43.932866,19.472011
12,A0A482MNW6_A,DNA cut related. Cas3 big hit,NaN,NaN,EC:1.2.1.58,0.0050,phenylglyoxilate dehydrogenase,EC:1.2.1.58,no,EC:1.2.1.58,...,6,10,0.785,redox_metabolism,A0A482MNW6,80,70.815006,82.868143,46.407011,12.053137
13,A0A5Q2W6X2_A,Serine--tRNA ligase,NaN,NaN,EC:4.2.1.2,0.0010,EC 4.2.1.2 (distance 0.0001): fumarate hydrata...,NaN,no,EC:4.2.1.2,...,5,8,0.811,translation_related,A0A5Q2W6X2,86,75.785522,86.839192,51.099639,11.053669
14,M4QSZ8_A,"Catalytic, pks?",NaN,NaN,EC:1.4.9.1,0.0118,methylamine dehydrogenase,NaN,no,EC:1.4.9.1,...,5,10,0.631,redox_metabolism,M4QSZ8,1308,73.483440,77.567226,38.062478,4.083785
15,A0A6J5MI62_A,Unclear function,NaN,NaN,EC:6.4.1.8,0.0010,EC 6.4.1.8 (distance 0.0010): acetophenone car...,NaN,no,EC:6.4.1.8,...,8,9,0.773,hydrogenase,A0A6J5MI62,56,61.088527,76.343882,44.760817,15.255355
16,A0A8D9FRS7_A,Photosystem catalystic,NaN,NaN,EC:3.1.3.84,0.0008,EC 3.1.3.84 (distance 0.0078): ADP-ribose 1''-...,NaN,no,EC:3.1.3.84,...,5,9,0.766,nuclease,A0A8D9FRS7,3,62.683418,79.506649,44.913670,16.823231
17,A0A3G5A0I1_A,Triphosphatase (thiamine?),NaN,NaN,EC:1.3.7.5,0.0006,EC 1.3.7.5 (distance 0.0061): phycocyanobilin:...,NaN,no,EC:1.3.7.5,...,6,10,0.759,redox_metabolism,A0A3G5A0I1,7,36.096728,82.366736,43.104946,46.270008
18,A0A0M4JB06_A,Complement C1qrealted,NaN,NaN,EC:3.4.21.97,0.5051,EC 3.4.21.97 (distance 0.5051): assemblin. | C...,NaN,no,EC:3.4.21.97,...,2,9,0.456,protease,A0A0M4JB06,10,58.985536,73.258238,41.666637,14.272702
19,A0A385E597_A,Tryptophan hydrolase OR elongation factor,NaN,NaN,EC:2.1.1.368,0.0002,EC:6.5.1.1/0.0001,EC 2.1.1.368 (distance 0.0002): [histone H3]-l...,no,EC:2.1.1.368,...,8,10,0.735,aromatic_aa_biosynth,A0A385E597,97,52.594706,69.680703,34.557023,17.085997
20,A0A3G5AFJ4_A,Phopsholipid scramblase,NaN,NaN,EC:2.7.7.48,0.0002,EC 2.7.7.48 (distance 0.0062): RNA-directed RN...,NaN,no,EC:2.7.7.48,...,2,6,0.677,polymerase,A0A3G5AFJ4,70,56.030883,69.569104,40.430630,13.538221
21,A0A6J5MQI4_A,isopropylmalate synthase,NaN,NaN,EC:4.7.1.1,0.0000,EC 4.7.1.1 (distance 0.0154): alpha-D-ribose 1...,NaN,no,EC:4.7.1.1,...,6,10,0.674,nucleotide_metabolism,A0A6J5MQI4,3458,40.173762,81.702192,50.415088,41.528430
22,A0A345MMR4_A,Unclear function,NaN,NaN,EC:2.1.1.56,0.0027,EC 2.1.1.56 (distance 0.0053): mRNA (guanine-N...,NaN,no,EC:2.1.1.56,...,2,8,0.575,mrna_capping,A0A345MMR4,38,39.956138,88.877453,42.532383,48.921315
23,A0A482MIZ7_A,Monooxygenase related,NaN,NaN,EC:3.1.21.4,0.1909,EC 3.1.21.4 (distance 0.0000): type II site-sp...,NaN,no,EC:3.1.21.4,...,3,7,0.136,restriction_nuclease,A0A482MIZ7,52,61.724104,71.589150,37.267517,9.865046
24,A0A6J5RXM6_A,Peptide chemistry,NaN,NaN,EC:2.1.1.318,0.0001,SAM chemistry,NaN,no,EC:2.1.1.318,...,3,6,0.372,other_or_unclear,A0A6J5RXM6,6,61.744257,82.749639,42.365022,21.005382
25,A0A1E1GDF1_A,No homolog fold,NaN,NaN,EC:2.5.1.151,0.0008,EC 2.5.1.151 (distance 0.0008): alkylcobalamin...,EC 2.5.1.151 (distance 0.0008): alkylcobalamin...,no,EC:2.5.1.151,...,4,10,0.288,redox_metabolism,A0A1E1GDF1,4,43.083242,79.095863,42.187233,36.012621
26,A0A8S5R1L7_A,New fold,NaN,NaN,EC:2.5.1.151,0.0015,EC 2.5.1.151 (distance 0.0008): alkylcobalamin...,EC 2.5.1.151 (distance 0.0015): alkylcobalamin...,no,EC:2.5.1.151,...,3,10,0.277,redox_metabolism,A0A8S5R1L7,52,48.525094,72.285701,33.036512,23.760608

In [23]:
# Export df_teo to Excel with embedded structure images (ESMFold vs ProteinTTT)
#
# This uses a separate conda env (ttt-export) that contains PyMOL + xlsxwriter.
from pathlib import Path
import subprocess
import textwrap

# Where structures live
# - ProteinTTT structures are in: res_dir/predicted_structures/ESMFold_ProteinTTT
# - Some datasets (e.g. bfvd_sample_best) have *truncated* ESMFold PDBs (1 byte, content "P").
#   In that case, we fall back to bfvd_sample where full ESMFold predictions exist.
dir_esmfold = res_dir / "predicted_structures" / "ESMFold"
dir_proteinttt = res_dir / "predicted_structures" / "ESMFold_ProteinTTT"

try:
    esm_sizes = [p.stat().st_size for p in dir_esmfold.glob("*.pdb")]
    if esm_sizes and max(esm_sizes) < 1000:
        fallback = res_dir.parent / "bfvd_sample" / "predicted_structures" / "ESMFold"
        if fallback.exists():
            dir_esmfold = fallback
except Exception:
    pass

out_dir = Path("/scratch/project/open-35-8/antonb/ttt/ProteinTTT/outputs/teo_excel_export")
img_dir = out_dir / "images"
out_dir.mkdir(parents=True, exist_ok=True)
img_dir.mkdir(parents=True, exist_ok=True)

csv_path = out_dir / "df_teo.csv"
xlsx_path = out_dir / "df_teo_with_structures.xlsx"
script_path = out_dir / "export_teo_excel_with_images.py"

df_teo.to_csv(csv_path, index=False)

script_path.write_text(
    textwrap.dedent(
        r'''
        import argparse
        from pathlib import Path

        import pandas as pd
        from PIL import Image, ImageDraw


        def find_structure(struct_dir: Path, protein_id: str) -> Path | None:
            if not struct_dir.exists():
                return None

            # Expected filenames look like: {id}_A.pdb
            hits = sorted(struct_dir.glob(f"{protein_id}_*.pdb"))
            if hits:
                return hits[0]

            # Fallbacks
            hits = sorted(struct_dir.glob(f"{protein_id}*.pdb"))
            if hits:
                return hits[0]

            hits = sorted(struct_dir.rglob(f"{protein_id}_*.pdb"))
            if hits:
                return hits[0]

            hits = sorted(struct_dir.rglob(f"{protein_id}*.pdb"))
            if hits:
                return hits[0]

            return None


        def write_placeholder_png(out_png: Path, label: str, size: int = 350) -> None:
            out_png.parent.mkdir(parents=True, exist_ok=True)
            im = Image.new("RGBA", (size, size), (255, 255, 255, 255))
            d = ImageDraw.Draw(im)
            d.rectangle([0, 0, size - 1, size - 1], outline=(180, 180, 180, 255), width=2)
            d.text((12, 12), "MISSING", fill=(200, 0, 0, 255))
            d.text((12, 40), label, fill=(0, 0, 0, 255))
            im.save(out_png)


        def pymol_render_png(cmd, pdb_path: Path, out_png: Path, size: int = 350) -> None:
            out_png.parent.mkdir(parents=True, exist_ok=True)

            cmd.delete("all")
            cmd.load(str(pdb_path), "m")
            cmd.hide("everything", "all")
            cmd.show("cartoon", "all")
            cmd.bg_color("white")
            cmd.set("ray_opaque_background", 0)

            # pLDDT is stored in B-factor; apply your discrete threshold palette
            cmd.set_color("n0", [0.051, 0.341, 0.827])
            cmd.set_color("n1", [0.416, 0.796, 0.945])
            cmd.set_color("n2", [0.996, 0.851, 0.212])
            cmd.set_color("n3", [0.992, 0.490, 0.302])
            cmd.color("n0", "b < 100")
            cmd.color("n1", "b < 90")
            cmd.color("n2", "b < 70")
            cmd.color("n3", "b < 50")

            cmd.orient("all")
            cmd.zoom("all")

            cmd.png(str(out_png), width=size, height=size, dpi=150, ray=1)


        def add_images_to_excel(df: pd.DataFrame, out_xlsx: Path, esm_imgs: list[Path], ttt_imgs: list[Path]) -> None:
            df_out = df.copy()
            col_esm = "ESMFold_structure"
            col_ttt = "ProteinTTT_structure"
            df_out[col_esm] = ""
            df_out[col_ttt] = ""

            with pd.ExcelWriter(out_xlsx, engine="xlsxwriter") as writer:
                df_out.to_excel(writer, index=False, sheet_name="teo")
                ws = writer.sheets["teo"]

                # Layout: make room for images
                img_col_width = 22
                img_row_height = 140

                esm_col_idx = df_out.columns.get_loc(col_esm)
                ttt_col_idx = df_out.columns.get_loc(col_ttt)
                ws.set_column(esm_col_idx, esm_col_idx, img_col_width)
                ws.set_column(ttt_col_idx, ttt_col_idx, img_col_width)

                # Data starts on row 1 (row 0 is the header)
                for i, (esm_png, ttt_png) in enumerate(zip(esm_imgs, ttt_imgs)):
                    excel_row = i + 1
                    ws.set_row(excel_row, img_row_height)

                    if esm_png.exists():
                        ws.insert_image(excel_row, esm_col_idx, str(esm_png), {"x_scale": 0.9, "y_scale": 0.9, "object_position": 1})
                    if ttt_png.exists():
                        ws.insert_image(excel_row, ttt_col_idx, str(ttt_png), {"x_scale": 0.9, "y_scale": 0.9, "object_position": 1})


        def main() -> None:
            ap = argparse.ArgumentParser()
            ap.add_argument("--csv", required=True)
            ap.add_argument("--esmfold-dir", required=True)
            ap.add_argument("--proteinttt-dir", required=True)
            ap.add_argument("--out-xlsx", required=True)
            ap.add_argument("--img-dir", required=True)
            args = ap.parse_args()

            csv_path = Path(args.csv)
            esm_dir = Path(args.esmfold_dir)
            ttt_dir = Path(args.proteinttt_dir)
            out_xlsx = Path(args.out_xlsx)
            img_dir = Path(args.img_dir)
            img_dir.mkdir(parents=True, exist_ok=True)

            df = pd.read_csv(csv_path)
            if "id" not in df.columns:
                raise ValueError("Expected an 'id' column in df_teo")

            # Launch PyMOL once
            import pymol

            pymol.finish_launching(["pymol", "-cq"])
            from pymol import cmd  # noqa: E402

            esm_imgs: list[Path] = []
            ttt_imgs: list[Path] = []

            for protein_id in df["id"].astype(str).tolist():
                esm_png = img_dir / f"{protein_id}__ESMFold.png"
                ttt_png = img_dir / f"{protein_id}__ProteinTTT.png"

                esm_pdb = find_structure(esm_dir, protein_id)
                ttt_pdb = find_structure(ttt_dir, protein_id)

                if esm_pdb is None:
                    write_placeholder_png(esm_png, f"ESMFold: {protein_id}")
                else:
                    pymol_render_png(cmd, esm_pdb, esm_png)

                if ttt_pdb is None:
                    write_placeholder_png(ttt_png, f"ProteinTTT: {protein_id}")
                else:
                    pymol_render_png(cmd, ttt_pdb, ttt_png)

                esm_imgs.append(esm_png)
                ttt_imgs.append(ttt_png)

            add_images_to_excel(df, out_xlsx, esm_imgs, ttt_imgs)

            cmd.quit()


        if __name__ == "__main__":
            main()
        '''
    ).lstrip()
)

# Ensure the export env exists (PyMOL + xlsxwriter). Creating it is a one-time step.
import json

def _ensure_conda_env(env_name: str = "ttt-export") -> None:
    envs_json = subprocess.run(
        ["conda", "env", "list", "--json"],
        check=True,
        capture_output=True,
        text=True,
    )
    env_paths = json.loads(envs_json.stdout).get("envs", [])
    if any(Path(p).name == env_name for p in env_paths):
        return

    print(f"Conda env '{env_name}' not found; creating it (this can take a few minutes)...")
    subprocess.run(
        [
            "conda",
            "create",
            "-y",
            "-n",
            env_name,
            "-c",
            "conda-forge",
            "python=3.11",
            "pymol-open-source",
            "pandas",
            "xlsxwriter",
            "pillow",
        ],
        check=True,
    )


_ensure_conda_env("ttt-export")

cmd = [
    "conda",
    "run",
    "-n",
    "ttt-export",
    "python",
    str(script_path),
    "--csv",
    str(csv_path),
    "--esmfold-dir",
    str(dir_esmfold),
    "--proteinttt-dir",
    str(dir_proteinttt),
    "--out-xlsx",
    str(xlsx_path),
    "--img-dir",
    str(img_dir),
]

print("Running:", " ".join(cmd))
subprocess.run(cmd, check=True)
print("Wrote:", xlsx_path)

Running: conda run -n ttt-export python /scratch/project/open-35-8/antonb/ttt/ProteinTTT/outputs/teo_excel_export/export_teo_excel_with_images.py --csv /scratch/project/open-35-8/antonb/ttt/ProteinTTT/outputs/teo_excel_export/df_teo.csv --esmfold-dir /scratch/project/open-35-8/pimenol1/ProteinTTT/ProteinTTT_fresh/data/bfvd/bfvd_sample/predicted_structures/ESMFold --proteinttt-dir /scratch/project/open-35-8/pimenol1/ProteinTTT/ProteinTTT_fresh/data/bfvd/bfvd_sample_best/predicted_structures/ESMFold_ProteinTTT --out-xlsx /scratch/project/open-35-8/antonb/ttt/ProteinTTT/outputs/teo_excel_export/df_teo_with_structures.xlsx --img-dir /scratch/project/open-35-8/antonb/ttt/ProteinTTT/outputs/teo_excel_export/images
Wrote: /scratch/project/open-35-8/antonb/ttt/ProteinTTT/outputs/teo_excel_export/df_teo_with_structures.xlsx

# Dec 2025

In [ ]:
# Set your sequence
sequence = "GIHLGELGLLPSTVLAIGYFENLVNIICESLNMLPKLEVSGKEYKKFKFTIVIPKDLDANIKKRAKIYFKQKSLIEIEIPTSSRNYPIHIQFDENSTDDILHLYDMPTTIGGIDKAIEMFMRKGHIGKTDQQKLLEERELRNFKTTLENLIATDAFAKEMVEVIIEE"

# Load model
model = esm.pretrained.esmfold_v1()
model = model.eval().cuda()

def predict_structure(model, sequence):
    with torch.no_grad():
        output = model.infer_pdb(sequence)

    with open("result.pdb", "w") as f:
        f.write(output)

    struct = bsio.load_structure("result.pdb", extra_fields=["b_factor"])
    print('pLDDT:', struct.b_factor.mean())

predict_structure(model, sequence)
# pLDDT: 38.43025

# ============ ProteinTTT =============
ttt_cfg = DEFAULT_ESMFOLD_TTT_CFG
model = ESMFoldTTT.ttt_from_pretrained(model, ttt_cfg=ttt_cfg, esmfold_config=model.cfg)
model.ttt(sequence)
# =====================================

predict_structure(model, sequence)
# pLDDT: 78.69619

# Reset model to original state (after this model.ttt can be called again on another protein)
# ============== ProteinTTT ===========
model.ttt_reset()
# =====================================

/scratch/project/open-35-8/antonb/miniconda3/envs/esmfold/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/scratch/project/open-35-8/antonb/miniconda3/envs/esmfold/lib/python3.10/site-packages/lightning_lite/__init__.py:29: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)
/scratch/project/open-35-8/antonb/miniconda3/envs/esmfold/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'repr' attribute with value False was provided to the `Field()` function, which has no effect in the context it was used. 'repr' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/scratch/project/open-35-8/antonb/miniconda3/envs/esmfold/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py:2249: UnsupportedFieldAttributeWarning: The 'frozen' attribute with value True was provided to the `Field()` function, which has no effect in the context it was used. 'frozen' is field-specific metadata, and can only be attached to a model field using `Annotated` metadata or by assignment. This may have happened because an `Annotated` type alias using the `type` statement was used, or if the `Field()` function was attached to a single member of a union type.
  warnings.warn(
/scratch/project/open-35-8/antonb/miniconda3/envs/esmfold/lib/python3.10/site-packages/torch/hub.py:338: UserWarning: TORCH_HUB is deprecated, please use env TORCH_HOME instead
  warnings.warn('TORCH_HUB is deprecated, please use env TORCH_HOME instead')

pLDDT: 38.430245170876674
2026-01-13 19:14:19,168 | INFO | step: 0, accumulated_step: 0, loss: None, perplexity: None, ttt_step_time: 0.00000, score_seq_time: 0.00000, eval_step_time: 1.76557, plddt: 38.43025
2026-01-13 19:14:21,512 | INFO | step: 1, accumulated_step: 4, loss: 2.54688, perplexity: None, ttt_step_time: 0.58051, score_seq_time: 0.00000, eval_step_time: 1.76197, plddt: 33.03000
2026-01-13 19:14:23,787 | INFO | step: 2, accumulated_step: 8, loss: 2.52148, perplexity: None, ttt_step_time: 0.51777, score_seq_time: 0.00000, eval_step_time: 1.75736, plddt: 34.36354
2026-01-13 19:14:26,063 | INFO | step: 3, accumulated_step: 12, loss: 2.48242, perplexity: None, ttt_step_time: 0.51855, score_seq_time: 0.00000, eval_step_time: 1.75633, plddt: 36.54465
2026-01-13 19:14:28,653 | INFO | step: 4, accumulated_step: 16, loss: 2.28516, perplexity: None, ttt_step_time: 0.51934, score_seq_time: 0.00000, eval_step_time: 1.75659, plddt: 77.43795
2026-01-13 19:14:30,937 | INFO | step: 5, accumulated_step: 20, loss: 2.39648, perplexity: None, ttt_step_time: 0.52427, score_seq_time: 0.00000, eval_step_time: 1.75739, plddt: 43.83944
2026-01-13 19:14:33,663 | INFO | step: 6, accumulated_step: 24, loss: 2.40234, perplexity: None, ttt_step_time: 0.52422, score_seq_time: 0.00000, eval_step_time: 1.75720, plddt: 78.79123
2026-01-13 19:14:35,945 | INFO | step: 7, accumulated_step: 28, loss: 2.14453, perplexity: None, ttt_step_time: 0.52488, score_seq_time: 0.00000, eval_step_time: 1.75575, plddt: 49.23912
2026-01-13 19:14:38,225 | INFO | step: 8, accumulated_step: 32, loss: 2.06641, perplexity: None, ttt_step_time: 0.52264, score_seq_time: 0.00000, eval_step_time: 1.75629, plddt: 75.38904
2026-01-13 19:14:40,504 | INFO | step: 9, accumulated_step: 36, loss: 1.91016, perplexity: None, ttt_step_time: 0.52234, score_seq_time: 0.00000, eval_step_time: 1.75617, plddt: 40.21620
2026-01-13 19:14:42,783 | INFO | step: 10, accumulated_step: 40, loss: 1.61621, perplexity: None, ttt_step_time: 0.52228, score_seq_time: 0.00000, eval_step_time: 1.75591, plddt: 38.10317
2026-01-13 19:14:45,061 | INFO | step: 11, accumulated_step: 44, loss: 1.29492, perplexity: None, ttt_step_time: 0.52202, score_seq_time: 0.00000, eval_step_time: 1.75538, plddt: 72.55406
2026-01-13 19:14:47,339 | INFO | step: 12, accumulated_step: 48, loss: 0.97607, perplexity: None, ttt_step_time: 0.52143, score_seq_time: 0.00000, eval_step_time: 1.75603, plddt: 39.89197
2026-01-13 19:14:49,618 | INFO | step: 13, accumulated_step: 52, loss: 0.71387, perplexity: None, ttt_step_time: 0.52236, score_seq_time: 0.00000, eval_step_time: 1.75612, plddt: 42.65030
2026-01-13 19:14:51,897 | INFO | step: 14, accumulated_step: 56, loss: 0.63330, perplexity: None, ttt_step_time: 0.52187, score_seq_time: 0.00000, eval_step_time: 1.75660, plddt: 38.79630
2026-01-13 19:14:54,175 | INFO | step: 15, accumulated_step: 60, loss: 0.32178, perplexity: None, ttt_step_time: 0.52221, score_seq_time: 0.00000, eval_step_time: 1.75581, plddt: 40.39759
2026-01-13 19:14:56,454 | INFO | step: 16, accumulated_step: 64, loss: 0.27905, perplexity: None, ttt_step_time: 0.52218, score_seq_time: 0.00000, eval_step_time: 1.75594, plddt: 37.91975
2026-01-13 19:14:58,733 | INFO | step: 17, accumulated_step: 68, loss: 0.05637, perplexity: None, ttt_step_time: 0.52234, score_seq_time: 0.00000, eval_step_time: 1.75603, plddt: 39.16910
2026-01-13 19:15:01,013 | INFO | step: 18, accumulated_step: 72, loss: 0.04068, perplexity: None, ttt_step_time: 0.52278, score_seq_time: 0.00000, eval_step_time: 1.75696, plddt: 38.90036
2026-01-13 19:15:03,300 | INFO | step: 19, accumulated_step: 76, loss: 0.01964, perplexity: None, ttt_step_time: 0.52980, score_seq_time: 0.00000, eval_step_time: 1.75657, plddt: 37.30368
2026-01-13 19:15:05,580 | INFO | step: 20, accumulated_step: 80, loss: 0.01431, perplexity: None, ttt_step_time: 0.52300, score_seq_time: 0.00000, eval_step_time: 1.75641, plddt: 37.29394
2026-01-13 19:15:07,861 | INFO | step: 21, accumulated_step: 84, loss: 0.00750, perplexity: None, ttt_step_time: 0.52319, score_seq_time: 0.00000, eval_step_time: 1.75628, plddt: 37.07651
2026-01-13 19:15:10,141 | INFO | step: 22, accumulated_step: 88, loss: 0.00585, perplexity: None, ttt_step_time: 0.52383, score_seq_time: 0.00000, eval_step_time: 1.75629, plddt: 37.40350
2026-01-13 19:15:12,420 | INFO | step: 23, accumulated_step: 92, loss: 0.00600, perplexity: None, ttt_step_time: 0.52196, score_seq_time: 0.00000, eval_step_time: 1.75593, plddt: 37.75507
2026-01-13 19:15:14,700 | INFO | step: 24, accumulated_step: 96, loss: 0.00597, perplexity: None, ttt_step_time: 0.52275, score_seq_time: 0.00000, eval_step_time: 1.75646, plddt: 36.97724
2026-01-13 19:15:16,978 | INFO | step: 25, accumulated_step: 100, loss: 0.00463, perplexity: None, ttt_step_time: 0.52216, score_seq_time: 0.00000, eval_step_time: 1.75596, plddt: 37.25671
2026-01-13 19:15:19,259 | INFO | step: 26, accumulated_step: 104, loss: 0.00359, perplexity: None, ttt_step_time: 0.52380, score_seq_time: 0.00000, eval_step_time: 1.75627, plddt: 38.26863
2026-01-13 19:15:21,537 | INFO | step: 27, accumulated_step: 108, loss: 0.00424, perplexity: None, ttt_step_time: 0.52218, score_seq_time: 0.00000, eval_step_time: 1.75548, plddt: 37.99968
2026-01-13 19:15:23,818 | INFO | step: 28, accumulated_step: 112, loss: 0.00335, perplexity: None, ttt_step_time: 0.52345, score_seq_time: 0.00000, eval_step_time: 1.75671, plddt: 41.61695
2026-01-13 19:15:26,098 | INFO | step: 29, accumulated_step: 116, loss: 0.00360, perplexity: None, ttt_step_time: 0.52310, score_seq_time: 0.00000, eval_step_time: 1.75635, plddt: 41.82556
2026-01-13 19:15:28,378 | INFO | step: 30, accumulated_step: 120, loss: 0.00285, perplexity: None, ttt_step_time: 0.52341, score_seq_time: 0.00000, eval_step_time: 1.75630, plddt: 41.20952
pLDDT: 78.79122585438336

In [5]:
uniprot_ids = [
    "G9E3N8",
    "G4YD72",
    "G3GP93"
]
sequences = [
    "MRVVVVMVVVVMVVVDLEVVVTAVVVVMVVARVVVDLEVVVTVVVRVEVAKAVVVMAVVVMAEGMVAEEKGEVMAGDLVVVVRAAADLAVVGLVAVVMVVEETVVVAMVVVETAVEGTVEVMVVGLVVVVTVVAGTVVAGTVVAGTVVVVMVAVMAAAVMVVVEMVVVGMAVVMVVVMVAVVTEEGLVVAMVVAVTEEGLVVEMVVVVTAAVMAVVVMAVVVMAVVVMAAGEKVIYQSE",
    "MRVVVVMVVVVMVVVDLEVVVTAVVVMVVVARVVVDLEVVVTVVVRVEVAKAVVVMAVVVMAEGMVAEEKGEVMAGDLVVVVRAAADLAVVGLVAVVMVVEETVVVAMVVVETAVEGTVEVMVVGLVVVVTVVAGTVVAGTVVAGTVVVVMVAVMAAAVMVVVEMVVVGMAVVMVVVMVAVVTEEGLVVAMVVAVTEEGLVVEMVVVVTAAVMAVVVMAVVVMAVVVMAAGEKVIYQSE",
    "MVAVAMAVVAMVVVDLVVVMAVAVMAAVDLAVAVMVVVMAAVAMAAVDLAAAVTVVAATVAVAMAMAMAMADLAVAEMVAVAMAATMVVAVTVAVTMAAVMAAAVMAVAVMAVGRWRWRWWRWWLGDGGGVMAVGVTAEAVMAVVEMVAAVMVVEAMVEVTVAVTVAADLVVVDLVVDLVEAVMVVAEGLGDNM"
]

In [6]:
ttt_cfg = DEFAULT_ESMFOLD_TTT_CFG
for uniprot_id, sequence in zip(uniprot_ids, sequences):
    for seed in range(3):
        print('uniprot_id', uniprot_id)
        print('sequence', sequence)
        print('seed', seed)
        ttt_cfg.seed = seed
        model.ttt_reset()
        model = ESMFoldTTT.ttt_from_pretrained(model, ttt_cfg=ttt_cfg, esmfold_config=model.cfg)
        model.ttt(sequence)
        predict_structure(model, sequence)

uniprot_id G9E3N8
sequence MRVVVVMVVVVMVVVDLEVVVTAVVVVMVVARVVVDLEVVVTVVVRVEVAKAVVVMAVVVMAEGMVAEEKGEVMAGDLVVVVRAAADLAVVGLVAVVMVVEETVVVAMVVVETAVEGTVEVMVVGLVVVVTVVAGTVVAGTVVAGTVVVVMVAVMAAAVMVVVEMVVVGMAVVMVVVMVAVVTEEGLVVAMVVAVTEEGLVVEMVVVVTAAVMAVVVMAVVVMAVVVMAAGEKVIYQSE
seed 0
2026-01-13 19:27:39,527 | INFO | step: 0, accumulated_step: 0, loss: None, perplexity: None, ttt_step_time: 0.00000, score_seq_time: 0.00000, eval_step_time: 3.25016, plddt: 32.21878
2026-01-13 19:27:43,381 | INFO | step: 1, accumulated_step: 4, loss: 0.93555, perplexity: None, ttt_step_time: 0.60923, score_seq_time: 0.00000, eval_step_time: 3.24422, plddt: 32.17507
2026-01-13 19:27:47,235 | INFO | step: 2, accumulated_step: 8, loss: 0.95508, perplexity: None, ttt_step_time: 0.61055, score_seq_time: 0.00000, eval_step_time: 3.24269, plddt: 31.73399
2026-01-13 19:27:51,089 | INFO | step: 3, accumulated_step: 12, loss: 1.10254, perplexity: None, ttt_step_time: 0.61004, score_seq_time: 0.00000, eval_step_time: 3.24307, plddt: 31.99118
2026-01-13 19:27:54,945 | INFO | step: 4, accumulated_step: 16, loss: 1.00000, perplexity: None, ttt_step_time: 0.61073, score_seq_time: 0.00000, eval_step_time: 3.24415, plddt: 31.83272
2026-01-13 19:27:58,797 | INFO | step: 5, accumulated_step: 20, loss: 0.88477, perplexity: None, ttt_step_time: 0.60962, score_seq_time: 0.00000, eval_step_time: 3.24240, plddt: 31.74766
2026-01-13 19:28:02,652 | INFO | step: 6, accumulated_step: 24, loss: 0.83496, perplexity: None, ttt_step_time: 0.61092, score_seq_time: 0.00000, eval_step_time: 3.24272, plddt: 31.57247
2026-01-13 19:28:06,506 | INFO | step: 7, accumulated_step: 28, loss: 0.78955, perplexity: None, ttt_step_time: 0.61034, score_seq_time: 0.00000, eval_step_time: 3.24357, plddt: 31.30677
2026-01-13 19:28:10,360 | INFO | step: 8, accumulated_step: 32, loss: 0.82715, perplexity: None, ttt_step_time: 0.61028, score_seq_time: 0.00000, eval_step_time: 3.24278, plddt: 31.30680
2026-01-13 19:28:14,212 | INFO | step: 9, accumulated_step: 36, loss: 0.80518, perplexity: None, ttt_step_time: 0.60851, score_seq_time: 0.00000, eval_step_time: 3.24246, plddt: 31.47917
2026-01-13 19:28:18,067 | INFO | step: 10, accumulated_step: 40, loss: 0.89209, perplexity: None, ttt_step_time: 0.61054, score_seq_time: 0.00000, eval_step_time: 3.24367, plddt: 31.13145
2026-01-13 19:28:21,920 | INFO | step: 11, accumulated_step: 44, loss: 0.81396, perplexity: None, ttt_step_time: 0.60999, score_seq_time: 0.00000, eval_step_time: 3.24275, plddt: 30.96279
2026-01-13 19:28:25,772 | INFO | step: 12, accumulated_step: 48, loss: 0.71338, perplexity: None, ttt_step_time: 0.60894, score_seq_time: 0.00000, eval_step_time: 3.24204, plddt: 30.33888
2026-01-13 19:28:29,625 | INFO | step: 13, accumulated_step: 52, loss: 0.70898, perplexity: None, ttt_step_time: 0.60828, score_seq_time: 0.00000, eval_step_time: 3.24339, plddt: 29.46299
2026-01-13 19:28:33,481 | INFO | step: 14, accumulated_step: 56, loss: 0.69824, perplexity: None, ttt_step_time: 0.60949, score_seq_time: 0.00000, eval_step_time: 3.24596, plddt: 29.16758
2026-01-13 19:28:37,339 | INFO | step: 15, accumulated_step: 60, loss: 0.78516, perplexity: None, ttt_step_time: 0.61237, score_seq_time: 0.00000, eval_step_time: 3.24550, plddt: 29.82802
2026-01-13 19:28:41,198 | INFO | step: 16, accumulated_step: 64, loss: 0.69287, perplexity: None, ttt_step_time: 0.61117, score_seq_time: 0.00000, eval_step_time: 3.24712, plddt: 30.44327
2026-01-13 19:28:45,052 | INFO | step: 17, accumulated_step: 68, loss: 0.47827, perplexity: None, ttt_step_time: 0.60931, score_seq_time: 0.00000, eval_step_time: 3.24315, plddt: 31.11760
2026-01-13 19:28:48,905 | INFO | step: 18, accumulated_step: 72, loss: 0.79102, perplexity: None, ttt_step_time: 0.60931, score_seq_time: 0.00000, eval_step_time: 3.24351, plddt: 28.61959
2026-01-13 19:28:52,760 | INFO | step: 19, accumulated_step: 76, loss: 0.42310, perplexity: None, ttt_step_time: 0.60964, score_seq_time: 0.00000, eval_step_time: 3.24385, plddt: 30.35231
2026-01-13 19:28:56,613 | INFO | step: 20, accumulated_step: 80, loss: 0.58643, perplexity: None, ttt_step_time: 0.60923, score_seq_time: 0.00000, eval_step_time: 3.24328, plddt: 29.24653
2026-01-13 19:29:00,465 | INFO | step: 21, accumulated_step: 84, loss: 0.58057, perplexity: None, ttt_step_time: 0.60842, score_seq_time: 0.00000, eval_step_time: 3.24296, plddt: 27.40160
2026-01-13 19:29:04,322 | INFO | step: 22, accumulated_step: 88, loss: 0.45654, perplexity: None, ttt_step_time: 0.61031, score_seq_time: 0.00000, eval_step_time: 3.24637, plddt: 30.54407
2026-01-13 19:29:08,175 | INFO | step: 23, accumulated_step: 92, loss: 0.63477, perplexity: None, ttt_step_time: 0.60885, score_seq_time: 0.00000, eval_step_time: 3.24339, plddt: 30.98537
2026-01-13 19:29:12,029 | INFO | step: 24, accumulated_step: 96, loss: 0.74023, perplexity: None, ttt_step_time: 0.61002, score_seq_time: 0.00000, eval_step_time: 3.24322, plddt: 29.08342
2026-01-13 19:29:15,884 | INFO | step: 25, accumulated_step: 100, loss: 0.43164, perplexity: None, ttt_step_time: 0.61060, score_seq_time: 0.00000, eval_step_time: 3.24362, plddt: 28.23830
2026-01-13 19:29:19,738 | INFO | step: 26, accumulated_step: 104, loss: 0.62158, perplexity: None, ttt_step_time: 0.61011, score_seq_time: 0.00000, eval_step_time: 3.24352, plddt: 30.47226
2026-01-13 19:29:23,594 | INFO | step: 27, accumulated_step: 108, loss: 0.38379, perplexity: None, ttt_step_time: 0.61083, score_seq_time: 0.00000, eval_step_time: 3.24400, plddt: 30.34944
2026-01-13 19:29:27,449 | INFO | step: 28, accumulated_step: 112, loss: 0.60547, perplexity: None, ttt_step_time: 0.61046, score_seq_time: 0.00000, eval_step_time: 3.24404, plddt: 30.53108
2026-01-13 19:29:31,303 | INFO | step: 29, accumulated_step: 116, loss: 0.62500, perplexity: None, ttt_step_time: 0.61020, score_seq_time: 0.00000, eval_step_time: 3.24272, plddt: 28.52065
2026-01-13 19:29:35,157 | INFO | step: 30, accumulated_step: 120, loss: 0.31421, perplexity: None, ttt_step_time: 0.61085, score_seq_time: 0.00000, eval_step_time: 3.24248, plddt: 29.88442
pLDDT: 32.21878063359235
uniprot_id G9E3N8
sequence MRVVVVMVVVVMVVVDLEVVVTAVVVVMVVARVVVDLEVVVTVVVRVEVAKAVVVMAVVVMAEGMVAEEKGEVMAGDLVVVVRAAADLAVVGLVAVVMVVEETVVVAMVVVETAVEGTVEVMVVGLVVVVTVVAGTVVAGTVVAGTVVVVMVAVMAAAVMVVVEMVVVGMAVVMVVVMVAVVTEEGLVVAMVVAVTEEGLVVEMVVVVTAAVMAVVVMAVVVMAVVVMAAGEKVIYQSE
seed 1
2026-01-13 19:30:12,602 | INFO | step: 0, accumulated_step: 0, loss: None, perplexity: None, ttt_step_time: 0.00000, score_seq_time: 0.00000, eval_step_time: 3.24965, plddt: 32.21878
2026-01-13 19:30:16,456 | INFO | step: 1, accumulated_step: 4, loss: 1.11328, perplexity: None, ttt_step_time: 0.60833, score_seq_time: 0.00000, eval_step_time: 3.24456, plddt: 31.88020
2026-01-13 19:30:20,311 | INFO | step: 2, accumulated_step: 8, loss: 0.87451, perplexity: None, ttt_step_time: 0.61091, score_seq_time: 0.00000, eval_step_time: 3.24284, plddt: 31.65948
2026-01-13 19:30:24,166 | INFO | step: 3, accumulated_step: 12, loss: 0.92773, perplexity: None, ttt_step_time: 0.61067, score_seq_time: 0.00000, eval_step_time: 3.24363, plddt: 31.92338
2026-01-13 19:30:28,022 | INFO | step: 4, accumulated_step: 16, loss: 0.81250, perplexity: None, ttt_step_time: 0.61137, score_seq_time: 0.00000, eval_step_time: 3.24398, plddt: 32.00990
2026-01-13 19:30:31,877 | INFO | step: 5, accumulated_step: 20, loss: 0.91553, perplexity: None, ttt_step_time: 0.61097, score_seq_time: 0.00000, eval_step_time: 3.24365, plddt: 32.10937
2026-01-13 19:30:35,733 | INFO | step: 6, accumulated_step: 24, loss: 0.82275, perplexity: None, ttt_step_time: 0.61114, score_seq_time: 0.00000, eval_step_time: 3.24391, plddt: 31.55556
2026-01-13 19:30:39,588 | INFO | step: 7, accumulated_step: 28, loss: 0.97461, perplexity: None, ttt_step_time: 0.61041, score_seq_time: 0.00000, eval_step_time: 3.24367, plddt: 31.55009
2026-01-13 19:30:43,442 | INFO | step: 8, accumulated_step: 32, loss: 0.89893, perplexity: None, ttt_step_time: 0.61068, score_seq_time: 0.00000, eval_step_time: 3.24326, plddt: 31.44528
2026-01-13 19:30:47,298 | INFO | step: 9, accumulated_step: 36, loss: 0.73975, perplexity: None, ttt_step_time: 0.61107, score_seq_time: 0.00000, eval_step_time: 3.24336, plddt: 31.41606
2026-01-13 19:30:51,152 | INFO | step: 10, accumulated_step: 40, loss: 0.85205, perplexity: None, ttt_step_time: 0.61070, score_seq_time: 0.00000, eval_step_time: 3.24276, plddt: 31.41140
2026-01-13 19:30:55,007 | INFO | step: 11, accumulated_step: 44, loss: 0.75684, perplexity: None, ttt_step_time: 0.61107, score_seq_time: 0.00000, eval_step_time: 3.24291, plddt: 31.19189
2026-01-13 19:30:58,862 | INFO | step: 12, accumulated_step: 48, loss: 0.64844, perplexity: None, ttt_step_time: 0.61091, score_seq_time: 0.00000, eval_step_time: 3.24397, plddt: 31.33230
2026-01-13 19:31:02,718 | INFO | step: 13, accumulated_step: 52, loss: 0.86133, perplexity: None, ttt_step_time: 0.61094, score_seq_time: 0.00000, eval_step_time: 3.24411, plddt: 29.80771
2026-01-13 19:31:06,573 | INFO | step: 14, accumulated_step: 56, loss: 0.72168, perplexity: None, ttt_step_time: 0.61122, score_seq_time: 0.00000, eval_step_time: 3.24365, plddt: 30.65140
2026-01-13 19:31:10,428 | INFO | step: 15, accumulated_step: 60, loss: 0.64014, perplexity: None, ttt_step_time: 0.61050, score_seq_time: 0.00000, eval_step_time: 3.24318, plddt: 29.08252
2026-01-13 19:31:14,284 | INFO | step: 16, accumulated_step: 64, loss: 0.73633, perplexity: None, ttt_step_time: 0.61110, score_seq_time: 0.00000, eval_step_time: 3.24399, plddt: 29.13822
2026-01-13 19:31:18,138 | INFO | step: 17, accumulated_step: 68, loss: 0.69531, perplexity: None, ttt_step_time: 0.61011, score_seq_time: 0.00000, eval_step_time: 3.24358, plddt: 30.49127
2026-01-13 19:31:21,993 | INFO | step: 18, accumulated_step: 72, loss: 0.52051, perplexity: None, ttt_step_time: 0.61074, score_seq_time: 0.00000, eval_step_time: 3.24355, plddt: 29.93136
2026-01-13 19:31:25,849 | INFO | step: 19, accumulated_step: 76, loss: 0.56201, perplexity: None, ttt_step_time: 0.61088, score_seq_time: 0.00000, eval_step_time: 3.24394, plddt: 29.04931
2026-01-13 19:31:29,704 | INFO | step: 20, accumulated_step: 80, loss: 0.54053, perplexity: None, ttt_step_time: 0.61102, score_seq_time: 0.00000, eval_step_time: 3.24326, plddt: 30.63947
2026-01-13 19:31:33,559 | INFO | step: 21, accumulated_step: 84, loss: 0.58447, perplexity: None, ttt_step_time: 0.61055, score_seq_time: 0.00000, eval_step_time: 3.24363, plddt: 31.03598
2026-01-13 19:31:37,413 | INFO | step: 22, accumulated_step: 88, loss: 0.71240, perplexity: None, ttt_step_time: 0.60996, score_seq_time: 0.00000, eval_step_time: 3.24353, plddt: 29.94579
2026-01-13 19:31:41,268 | INFO | step: 23, accumulated_step: 92, loss: 0.47827, perplexity: None, ttt_step_time: 0.61057, score_seq_time: 0.00000, eval_step_time: 3.24365, plddt: 29.33192
2026-01-13 19:31:45,124 | INFO | step: 24, accumulated_step: 96, loss: 0.47046, perplexity: None, ttt_step_time: 0.61118, score_seq_time: 0.00000, eval_step_time: 3.24391, plddt: 28.97331
2026-01-13 19:31:48,980 | INFO | step: 25, accumulated_step: 100, loss: 0.35669, perplexity: None, ttt_step_time: 0.61134, score_seq_time: 0.00000, eval_step_time: 3.24441, plddt: 28.95897
2026-01-13 19:31:52,836 | INFO | step: 26, accumulated_step: 104, loss: 0.44897, perplexity: None, ttt_step_time: 0.61202, score_seq_time: 0.00000, eval_step_time: 3.24334, plddt: 28.52005
2026-01-13 19:31:56,691 | INFO | step: 27, accumulated_step: 108, loss: 0.68262, perplexity: None, ttt_step_time: 0.61049, score_seq_time: 0.00000, eval_step_time: 3.24334, plddt: 28.07403
2026-01-13 19:32:00,549 | INFO | step: 28, accumulated_step: 112, loss: 0.61328, perplexity: None, ttt_step_time: 0.61009, score_seq_time: 0.00000, eval_step_time: 3.24672, plddt: 30.21262
2026-01-13 19:32:04,407 | INFO | step: 29, accumulated_step: 116, loss: 0.63525, perplexity: None, ttt_step_time: 0.61142, score_seq_time: 0.00000, eval_step_time: 3.24625, plddt: 28.53134
2026-01-13 19:32:08,261 | INFO | step: 30, accumulated_step: 120, loss: 0.30811, perplexity: None, ttt_step_time: 0.61041, score_seq_time: 0.00000, eval_step_time: 3.24307, plddt: 28.47882
pLDDT: 32.21878063359235
uniprot_id G9E3N8
sequence MRVVVVMVVVVMVVVDLEVVVTAVVVVMVVARVVVDLEVVVTVVVRVEVAKAVVVMAVVVMAEGMVAEEKGEVMAGDLVVVVRAAADLAVVGLVAVVMVVEETVVVAMVVVETAVEGTVEVMVVGLVVVVTVVAGTVVAGTVVAGTVVVVMVAVMAAAVMVVVEMVVVGMAVVMVVVMVAVVTEEGLVVAMVVAVTEEGLVVEMVVVVTAAVMAVVVMAVVVMAVVVMAAGEKVIYQSE
seed 2
2026-01-13 19:32:45,675 | INFO | step: 0, accumulated_step: 0, loss: None, perplexity: None, ttt_step_time: 0.00000, score_seq_time: 0.00000, eval_step_time: 3.24919, plddt: 32.21878
2026-01-13 19:32:49,529 | INFO | step: 1, accumulated_step: 4, loss: 0.97461, perplexity: None, ttt_step_time: 0.60878, score_seq_time: 0.00000, eval_step_time: 3.24406, plddt: 32.11390
2026-01-13 19:32:53,383 | INFO | step: 2, accumulated_step: 8, loss: 1.01172, perplexity: None, ttt_step_time: 0.60995, score_seq_time: 0.00000, eval_step_time: 3.24313, plddt: 31.91582
2026-01-13 19:32:57,237 | INFO | step: 3, accumulated_step: 12, loss: 0.94482, perplexity: None, ttt_step_time: 0.60955, score_seq_time: 0.00000, eval_step_time: 3.24395, plddt: 31.93997
2026-01-13 19:33:01,092 | INFO | step: 4, accumulated_step: 16, loss: 0.95752, perplexity: None, ttt_step_time: 0.60929, score_seq_time: 0.00000, eval_step_time: 3.24407, plddt: 31.86467
2026-01-13 19:33:04,946 | INFO | step: 5, accumulated_step: 20, loss: 0.88477, perplexity: None, ttt_step_time: 0.61026, score_seq_time: 0.00000, eval_step_time: 3.24345, plddt: 31.66044
2026-01-13 19:33:08,800 | INFO | step: 6, accumulated_step: 24, loss: 0.89746, perplexity: None, ttt_step_time: 0.60993, score_seq_time: 0.00000, eval_step_time: 3.24339, plddt: 31.41712
2026-01-13 19:33:12,654 | INFO | step: 7, accumulated_step: 28, loss: 0.90723, perplexity: None, ttt_step_time: 0.60950, score_seq_time: 0.00000, eval_step_time: 3.24357, plddt: 31.40028
2026-01-13 19:33:16,507 | INFO | step: 8, accumulated_step: 32, loss: 0.85645, perplexity: None, ttt_step_time: 0.60893, score_seq_time: 0.00000, eval_step_time: 3.24339, plddt: 31.30821
2026-01-13 19:33:20,362 | INFO | step: 9, accumulated_step: 36, loss: 0.94434, perplexity: None, ttt_step_time: 0.60970, score_seq_time: 0.00000, eval_step_time: 3.24417, plddt: 31.68252
2026-01-13 19:33:24,216 | INFO | step: 10, accumulated_step: 40, loss: 0.83594, perplexity: None, ttt_step_time: 0.60968, score_seq_time: 0.00000, eval_step_time: 3.24333, plddt: 31.47956
2026-01-13 19:33:28,068 | INFO | step: 11, accumulated_step: 44, loss: 0.65967, perplexity: None, ttt_step_time: 0.60884, score_seq_time: 0.00000, eval_step_time: 3.24320, plddt: 31.11884
2026-01-13 19:33:31,921 | INFO | step: 12, accumulated_step: 48, loss: 0.68652, perplexity: None, ttt_step_time: 0.60914, score_seq_time: 0.00000, eval_step_time: 3.24287, plddt: 31.07734
2026-01-13 19:33:35,776 | INFO | step: 13, accumulated_step: 52, loss: 0.83740, perplexity: None, ttt_step_time: 0.60985, score_seq_time: 0.00000, eval_step_time: 3.24379, plddt: 30.12749
2026-01-13 19:33:39,629 | INFO | step: 14, accumulated_step: 56, loss: 0.77246, perplexity: None, ttt_step_time: 0.60967, score_seq_time: 0.00000, eval_step_time: 3.24349, plddt: 29.78772
2026-01-13 19:33:43,482 | INFO | step: 15, accumulated_step: 60, loss: 0.70898, perplexity: None, ttt_step_time: 0.60956, score_seq_time: 0.00000, eval_step_time: 3.24250, plddt: 30.42720
2026-01-13 19:33:47,336 | INFO | step: 16, accumulated_step: 64, loss: 0.60742, perplexity: None, ttt_step_time: 0.60990, score_seq_time: 0.00000, eval_step_time: 3.24317, plddt: 30.30001
2026-01-13 19:33:51,189 | INFO | step: 17, accumulated_step: 68, loss: 0.63477, perplexity: None, ttt_step_time: 0.60887, score_seq_time: 0.00000, eval_step_time: 3.24355, plddt: 30.08317
2026-01-13 19:33:55,043 | INFO | step: 18, accumulated_step: 72, loss: 0.52930, perplexity: None, ttt_step_time: 0.60967, score_seq_time: 0.00000, eval_step_time: 3.24370, plddt: 30.27793
2026-01-13 19:33:58,897 | INFO | step: 19, accumulated_step: 76, loss: 0.52246, perplexity: None, ttt_step_time: 0.60932, score_seq_time: 0.00000, eval_step_time: 3.24379, plddt: 30.72577
2026-01-13 19:34:02,750 | INFO | step: 20, accumulated_step: 80, loss: 0.54004, perplexity: None, ttt_step_time: 0.60941, score_seq_time: 0.00000, eval_step_time: 3.24278, plddt: 28.72355
2026-01-13 19:34:06,604 | INFO | step: 21, accumulated_step: 84, loss: 0.51758, perplexity: None, ttt_step_time: 0.60962, score_seq_time: 0.00000, eval_step_time: 3.24301, plddt: 29.76579
2026-01-13 19:34:10,458 | INFO | step: 22, accumulated_step: 88, loss: 0.51074, perplexity: None, ttt_step_time: 0.60960, score_seq_time: 0.00000, eval_step_time: 3.24362, plddt: 31.03292
2026-01-13 19:34:14,311 | INFO | step: 23, accumulated_step: 92, loss: 0.72900, perplexity: None, ttt_step_time: 0.60941, score_seq_time: 0.00000, eval_step_time: 3.24313, plddt: 29.82874
2026-01-13 19:34:18,164 | INFO | step: 24, accumulated_step: 96, loss: 0.64502, perplexity: None, ttt_step_time: 0.60971, score_seq_time: 0.00000, eval_step_time: 3.24226, plddt: 29.98203
2026-01-13 19:34:22,018 | INFO | step: 25, accumulated_step: 100, loss: 0.55273, perplexity: None, ttt_step_time: 0.60992, score_seq_time: 0.00000, eval_step_time: 3.24339, plddt: 29.26858
2026-01-13 19:34:25,870 | INFO | step: 26, accumulated_step: 104, loss: 0.42529, perplexity: None, ttt_step_time: 0.60890, score_seq_time: 0.00000, eval_step_time: 3.24302, plddt: 29.06654
2026-01-13 19:34:29,723 | INFO | step: 27, accumulated_step: 108, loss: 0.60303, perplexity: None, ttt_step_time: 0.60952, score_seq_time: 0.00000, eval_step_time: 3.24280, plddt: 29.79547
2026-01-13 19:34:33,577 | INFO | step: 28, accumulated_step: 112, loss: 0.35962, perplexity: None, ttt_step_time: 0.60949, score_seq_time: 0.00000, eval_step_time: 3.24320, plddt: 30.04257
2026-01-13 19:34:37,429 | INFO | step: 29, accumulated_step: 116, loss: 0.26416, perplexity: None, ttt_step_time: 0.60939, score_seq_time: 0.00000, eval_step_time: 3.24251, plddt: 28.18159
2026-01-13 19:34:41,283 | INFO | step: 30, accumulated_step: 120, loss: 0.23608, perplexity: None, ttt_step_time: 0.60943, score_seq_time: 0.00000, eval_step_time: 3.24319, plddt: 29.94462
pLDDT: 32.21878063359235
uniprot_id G4YD72
sequence MRVVVVMVVVVMVVVDLEVVVTAVVVMVVVARVVVDLEVVVTVVVRVEVAKAVVVMAVVVMAEGMVAEEKGEVMAGDLVVVVRAAADLAVVGLVAVVMVVEETVVVAMVVVETAVEGTVEVMVVGLVVVVTVVAGTVVAGTVVAGTVVVVMVAVMAAAVMVVVEMVVVGMAVVMVVVMVAVVTEEGLVVAMVVAVTEEGLVVEMVVVVTAAVMAVVVMAVVVMAVVVMAAGEKVIYQSE
seed 0
2026-01-13 19:35:18,703 | INFO | step: 0, accumulated_step: 0, loss: None, perplexity: None, ttt_step_time: 0.00000, score_seq_time: 0.00000, eval_step_time: 3.24954, plddt: 31.94426
2026-01-13 19:35:22,556 | INFO | step: 1, accumulated_step: 4, loss: 0.98828, perplexity: None, ttt_step_time: 0.60899, score_seq_time: 0.00000, eval_step_time: 3.24359, plddt: 31.62082
2026-01-13 19:35:26,410 | INFO | step: 2, accumulated_step: 8, loss: 0.99707, perplexity: None, ttt_step_time: 0.60936, score_seq_time: 0.00000, eval_step_time: 3.24355, plddt: 31.81569
2026-01-13 19:35:30,263 | INFO | step: 3, accumulated_step: 12, loss: 0.96924, perplexity: None, ttt_step_time: 0.60921, score_seq_time: 0.00000, eval_step_time: 3.24300, plddt: 31.47120
2026-01-13 19:35:34,117 | INFO | step: 4, accumulated_step: 16, loss: 0.90039, perplexity: None, ttt_step_time: 0.60989, score_seq_time: 0.00000, eval_step_time: 3.24307, plddt: 31.41198
2026-01-13 19:35:37,969 | INFO | step: 5, accumulated_step: 20, loss: 0.92383, perplexity: None, ttt_step_time: 0.60897, score_seq_time: 0.00000, eval_step_time: 3.24257, plddt: 31.77806
2026-01-13 19:35:41,822 | INFO | step: 6, accumulated_step: 24, loss: 0.85938, perplexity: None, ttt_step_time: 0.60952, score_seq_time: 0.00000, eval_step_time: 3.24303, plddt: 31.22826